pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('pharmacy/', include('pharmacyapp.urls')),
    path('', RedirectView.as_view(url='pharmacy/')),
    path('admin/', admin.site.urls),
]

pharmacyapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_index, name='index'),
    path('medicine/', views.MedicineListView.as_view(), name='medicine-list'),
    path('medicine/create', views.MedicineCreateView.as_view(), name='medicine-create'),
    path('medicine/delete/<int:pk>', views.MedicineDeleteView.as_view(), name='medicine-delete'),
    path('medicine/update/<int:pk>', views.MedicineUpdateView.as_view(), name='medicine-update'),
    path('medicine/detail/<int:pk>', views.MedicineDetailView.as_view(), name='medicine-detail'),
    path('medicine/price/create/<int:pk1>', views.PriceCreateView.as_view(), name='medicine-price-create'),
    path('medicine/price/update/<int:pk>/<int:pk1>', views.PriceUpdateView.as_view(), name='medicine-price-update'),
    path('medicine/price/delete/<int:pk>/<int:pk1>', views.PriceDeleteView.as_view(), name='medicine-price-delete'),
    path('dealer/', views.DealerListView.as_view(), name='dealer-list'),
    path('dealer/detail/<int:pk>', views.DealerDetailView.as_view(), name='dealer-detail'),
    path('dealer/create', views.DealerCreateView.as_view(), name='dealer-create'),
    path('dealer/update/<int:pk>', views.DealerUpdateView.as_view(), name='dealer-update'),
    path('dealer/delete/<int:pk>', views.DealerDeleteView.as_view(), name='dealer-delete'),
    path('employee/', views.EmployeeListView.as_view(), name='employee-list'),
    path('employee/detail/<int:pk>', views.EmployeeDetailView.as_view(), name='employee-detail'),
    path('employee/create', views.EmployeeCreateView.as_view(), name='employee-create'),
    path('employee/update/<int:pk>', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee/delete/<int:pk>', views.EmployeeDeleteView.as_view(), name='employee-delete'),
    path('todo/', views.TodoListView.as_view(), name='todo-list'),
    path('todo/create', views.TodoCreateView.as_view(), name='todo-create'),
    path('todo/delete/<int:pk>', views.TodoDeleteView.as_view(), name='todo-delete'),
    path('todo/update/<int:pk>', views.TodoUpdateView.as_view(), name='todo-update'),
    path('todo/detail/<int:pk>', views.TodoDetailView.as_view(), name='todo-detail'),
    path('attendance/', views.AttendanceListView.as_view(), name='attendance-list'),
    path('attendance/create', views.AttendanceCreateView.as_view(), name='attendance-create'),
    path('attendance/delete/<int:pk>', views.AttendanceDeleteView.as_view(), name='attendance-delete'),
    path('attendance/update/<int:pk>', views.AttendanceUpdateView.as_view(), name='attendance-update'),
    path('attendance/detail/<int:pk>', views.AttendanceDetailView.as_view(), name='attendance-detail'),
    path('bill/', views.BillListView.as_view(), name='bill-list'),
    path('bill/create', views.BillCreateView.as_view(), name='bill-create'),
    path('bill/delete/<int:pk>', views.BillDeleteView.as_view(), name='bill-delete'),
    path('bill/update/<int:pk>', views.BillUpdateView.as_view(), name='bill-update'),
    path('bill/detail/<int:pk>', views.BillDetailView.as_view(), name='bill-detail'),
    path('customer/', views.CustomerListView.as_view(), name='customer-list'),
    path('customer/create', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customer/delete/<int:pk>', views.CustomerDeleteView.as_view(), name='customer-delete'),
    path('customer/update/<int:pk>', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/detail/<int:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('pharmacy/', views.PharmacyUpdateView.as_view(), {'pk': 1}, name='pharmacy',),
]

pharmacyapp/models.py
from django.db import models
from django.urls import reverse


class Pharmacy(models.Model):
    """Model representing a Pharmacy."""
    shop_name = models.CharField(max_length=300)
    address = models.TextField()
    owner_name = models.CharField(max_length=300)
    phone_no = models.DecimalField(max_digits=11, decimal_places=0, null=True)


class Medicine(models.Model):
    """Model representing a Medicine."""
    code = models.DecimalField(max_digits=5, decimal_places=0)
    name = models.CharField(max_length=200)
    stock = models.DecimalField(max_digits=6, decimal_places=0)
    description = models.TextField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('medicine-detail', args=[str(self.id)])


class Price(models.Model):
    """Model representing a Medicine's Price"""
    medicine = models.ForeignKey('Medicine',on_delete=models.CASCADE)
    dealer = models.ForeignKey('Dealer',on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)


class Dealer(models.Model):
    """Model representing a Dealer."""
    name = models.CharField(max_length=300)
    address = models.TextField()
    phone_no = models.DecimalField(max_digits=11, decimal_places=0)
    email = models.EmailField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dealer-detail', args=[str(self.id)])


class Employee(models.Model):
    """Model representing a Employee"""
    name = models.CharField(max_length=200)
    address = models.TextField()
    phone_no = models.DecimalField(max_digits=11, decimal_places=0)
    email = models.EmailField()
    PROOF = (
        ('a', 'Aadhar'),
        ('b', 'Driving License'),
        ('c', 'Ration Card'),
        ('d', 'PAN Card'),
        ('e', 'Passport'),
    )
    id_proof = models.CharField(
        max_length=1,
        choices=PROOF,
        blank=False,
        default='a',
        help_text='Enter Vote',
    )
    proof_unique_no = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('employee-detail', args=[str(self.id)])


class TODO(models.Model):
    """Model representing a TODO"""
    title = models.CharField(max_length=200)
    date = models.DateField()
    employees = models.ManyToManyField('Employee', blank=True)
    description = models.TextField(max_length=1000)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo-detail', args=[str(self.id)])


class Customer(models.Model):
    """Model representing a Customer"""
    name = models.CharField(max_length=200)
    address = models.TextField()
    phone_no = models.DecimalField(max_digits=11, decimal_places=0)
    email = models.EmailField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('customer-detail', args=[str(self.id)])


class Bill(models.Model):
    """Model representing a Bill"""
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField()
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.customer.name

    def get_absolute_url(self):
        return reverse('bill-detail', args=[str(self.id)])


class Attendance(models.Model):
    """Model representing a Attendance"""
    date = models.DateField()
    employees = models.ManyToManyField('Employee', blank=True)

    class Meta:
        ordering = ['date']

    def get_absolute_url(self):
        return reverse('attendance-detail', args=[str(self.id)])

    def __str__(self):
        return str(self.date)

pharmacyapp/views.py
from django.shortcuts import render
from .models import Medicine, Employee, Dealer, Price, Pharmacy, TODO, Attendance, Bill, Customer
from django.views import generic
from django.urls import reverse_lazy
from django_filters import views
from .filters import MedicineFilter, DealerFilter, EmployeeFilter, TodoFilter, AttendanceFilter, BillFilter, CustomerFilter


def show_index(request):
    context = {
        'No_Of_Medicine': Medicine.objects.all().count(),
        'No_Of_Bill': Bill.objects.all().count(),
        'No_Of_Customer': Customer.objects.all().count(),
        'No_Of_Dealer': Dealer.objects.all().count(),
        'No_Of_Employee': Employee.objects.all().count(),
        'No_Of_TODO': TODO.objects.all().count(),
    }
    return render(request, 'pharmacyapp/index.html', context)


class MedicineListView(views.FilterView):
    filterset_class = MedicineFilter
    paginate_by = 10
    template_name = 'pharmacyapp/medicine_list.html'


class MedicineCreateView(generic.CreateView):
    model = Medicine
    fields = ['code', 'name', 'stock', 'description']
    success_url = reverse_lazy('medicine-list')


class MedicineDeleteView(generic.DeleteView):
    model = Medicine
    success_url = reverse_lazy('medicine-list')


class MedicineUpdateView(generic.UpdateView):
    model = Medicine
    fields = ['code', 'name', 'stock', 'description']
    success_url = reverse_lazy('medicine-list')


class MedicineDetailView(generic.DetailView):
    model = Medicine


class PriceCreateView(generic.CreateView):
    model = Price
    fields = ['dealer','price']

    def form_valid(self, form):
        form.instance.medicine = Medicine.objects.get(pk=self.kwargs['pk1'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('medicine-detail', kwargs={'pk':self.kwargs['pk1']})


class PriceUpdateView(generic.UpdateView):
    model = Price
    fields = ['dealer', 'price']

    def get_success_url(self):
        return reverse_lazy('medicine-detail', kwargs={'pk':self.kwargs['pk1']})


class PriceDeleteView(generic.DeleteView):
    model = Price

    def get_success_url(self):
        return reverse_lazy('medicine-detail', kwargs={'pk':self.kwargs['pk1']})


class DealerDetailView(generic.DetailView):
    model = Dealer


class DealerListView(views.FilterView):
    filterset_class = DealerFilter
    paginate_by = 10
    template_name = 'pharmacyapp/dealer_list.html'


class DealerCreateView(generic.CreateView):
    model = Dealer
    fields = ['name', 'address', 'phone_no', 'email']
    success_url = reverse_lazy('dealer-list')


class DealerUpdateView(generic.UpdateView):
    model = Dealer
    fields = ['name', 'address', 'phone_no', 'email']
    success_url = reverse_lazy('dealer-list')


class DealerDeleteView(generic.DeleteView):
    model = Dealer
    success_url = reverse_lazy('dealer-list')


class EmployeeDetailView(generic.DetailView):
    model = Employee


class EmployeeListView(views.FilterView):
    filterset_class = EmployeeFilter
    paginate_by = 10
    template_name = 'pharmacyapp/employee_list.html'


class EmployeeCreateView(generic.CreateView):
    model = Employee
    fields = ['name', 'address', 'phone_no', 'email', 'id_proof', 'proof_unique_no']
    success_url = reverse_lazy('employee-list')


class EmployeeUpdateView(generic.UpdateView):
    model = Employee
    fields = ['name', 'address', 'phone_no', 'email', 'id_proof', 'proof_unique_no']
    success_url = reverse_lazy('employee-list')


class EmployeeDeleteView(generic.DeleteView):
    model = Employee
    success_url = reverse_lazy('employee-list')


class TodoListView(views.FilterView):
    filterset_class = TodoFilter
    paginate_by = 10
    template_name = 'pharmacyapp/todo_list.html'


class TodoCreateView(generic.CreateView):
    model = TODO
    fields = ['title', 'date', 'employees', 'description']
    success_url = reverse_lazy('todo-list')


class TodoDeleteView(generic.DeleteView):
    model = TODO
    success_url = reverse_lazy('todo-list')


class TodoUpdateView(generic.UpdateView):
    model = TODO
    fields = ['title', 'date', 'employees', 'description']
    success_url = reverse_lazy('todo-list')


class TodoDetailView(generic.DetailView):
    model = TODO


class PharmacyUpdateView(generic.UpdateView):
    model = Pharmacy
    fields = ['shop_name', 'address', 'owner_name', 'phone_no']
    success_url = reverse_lazy('index')


class AttendanceListView(views.FilterView):
    filterset_class = AttendanceFilter
    paginate_by = 10
    template_name = 'pharmacyapp/attendance_list.html'


class AttendanceCreateView(generic.CreateView):
    model = Attendance
    fields = ['date', 'employees']
    success_url = reverse_lazy('attendance-list')


class AttendanceDeleteView(generic.DeleteView):
    model = Attendance
    success_url = reverse_lazy('attendance-list')


class AttendanceUpdateView(generic.UpdateView):
    model = Attendance
    fields = ['date', 'employees']
    success_url = reverse_lazy('attendance-list')


class AttendanceDetailView(generic.DetailView):
    model = Attendance


class BillListView(views.FilterView):
    filterset_class = BillFilter
    paginate_by = 10
    template_name = 'pharmacyapp/bill_list.html'


class BillCreateView(generic.CreateView):
    model = Bill
    fields = ['customer', 'amount', 'date', 'employee']
    success_url = reverse_lazy('bill-list')


class BillDeleteView(generic.DeleteView):
    model = Bill
    success_url = reverse_lazy('bill-list')


class BillUpdateView(generic.UpdateView):
    model = Bill
    fields = ['customer', 'amount', 'date', 'employee']
    success_url = reverse_lazy('bill-list')


class BillDetailView(generic.DetailView):
    model = Bill


class CustomerListView(views.FilterView):
    filterset_class = CustomerFilter
    paginate_by = 10
    template_name = 'pharmacyapp/customer_list.html'


class CustomerCreateView(generic.CreateView):
    model = Customer
    fields = ['name', 'address', 'phone_no', 'email']
    success_url = reverse_lazy('customer-list')


class CustomerDeleteView(generic.DeleteView):
    model = Customer
    success_url = reverse_lazy('customer-list')


class CustomerUpdateView(generic.UpdateView):
    model = Customer
    fields = ['name', 'address', 'phone_no', 'email']
    success_url = reverse_lazy('customer-list')


class CustomerDetailView(generic.DetailView):
    model = Customer

pharmacyapp/templates/pharmacyapp/attendance_form.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/attendance_form_styles.css' %}">
    <div>
        <h1>Attendance</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

pharmacyapp/templates/pharmacyapp/attendance_list.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/attendance_list_styles.css' %}">
    <div>
        <button class="cust-button" onclick="location.href='{% url 'attendance-create' %}';">Create Attendance</button>
    </div>
    <br>
    <h1>Attendance</h1>
    <form method="get">
        <table>
        {{ filter.form.as_table }}
        </table>
        <input type="submit" />
    </form>
    {% if object_list %}
        <ul class="list-group">
        {% for attendance in page_obj %}
            <li class="list-med-item list-group-item" style="background-color:#ECE5F0; border-radius: 50px; justify-content: center;">
                <div class="container">
                <div class="row" style="justify-content: space-around;">
                    <div class="row-sm">
                    <a href="{% url 'attendance-detail' attendance.id %}">{{ attendance.date }}</a>
                    </div>
                    <div class="row-sm">
                        <button class="cust-button" onclick="location.href='{% url 'attendance-delete' attendance.id %}';">Delete</button>
                    </div>
                    <div class="row-sm">
                        <button class="cust-button" onclick="location.href='{% url 'attendance-update' attendance.id %}';">Update</button>
                    </div>
                </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    {% else %}
      <p>There are no attendance records in this application.</p>
    {% endif %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

pharmacyapp/templates/pharmacyapp/bill_form.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bill_form_styles.css' %}">
    <div>
        <h1>Bill</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

pharmacyapp/templates/pharmacyapp/customer_confirm_delete.html
{% extends "base-generic.html" %}

{% block content %}
<br>
<form method="post">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/customer_confirm_delete_styles.css' %}">
    {% csrf_token %}
    <h1>Customer Delete</h1>
    <p>Are you sure you want to delete "{{ object.date }}" this customer?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

pharmacyapp/templates/pharmacyapp/customer_detail.html
{% extends "base-generic.html" %}

{% block content %}
    <br>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/customer_detail_styles.css' %}">
    <h1>Customer</h1>
    <div style="margin: 10px;">
        <button class="cust-button" onclick="location.href='{% url "customer-update" customer.id %}';">Update Employee</button>
        <button class="cust-button" onclick="location.href='{% url "customer-delete" customer.id %}';">Delete Employee</button>
    </div>
    <div class="bord">
        <br>
        <h6>Name : <span> {{ customer.name }} </span> </h6>
        <h6>Address : <span> {{ customer.address }} </span> </h6>
        <h6>Phone No : <span> {{ customer.phone_no }} </span> </h6>
        <h6>Email : <span> {{ customer.email }} </span> </h6>
        <br>
    </div>
{% endblock %}

pharmacyapp/templates/pharmacyapp/customer_list.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/customer_list_styles.css' %}">
    <div>
        <button class="cust-button" onclick="location.href='{% url 'customer-create' %}';">Create Customer</button>
    </div>
    <br>
    <h1>Customer</h1>
    <form method="get">
        <table>
        {{ filter.form.as_table }}
        </table>
        <input type="submit" />
    </form>
    {% if object_list %}
        <ul class="list-group">
        {% for customer in page_obj %}
            <li class="list-med-item list-group-item" style="background-color:#ECE5F0; border-radius: 50px; justify-content: center;">
                <div class="container">
                <div class="row" style="justify-content: space-around;">
                    <div class="row-sm">
                    <a href="{% url 'customer-detail' customer.id %}">{{ customer.name }}</a>
                    </div>
                    <div class="row-sm">
                        <button class="cust-button" onclick="location.href='{% url 'customer-delete' customer.id %}';">Delete</button>
                    </div>
                    <div class="row-sm">
                        <button class="cust-button" onclick="location.href='{% url 'customer-update' customer.id %}';">Update</button>
                    </div>
                </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    {% else %}
      <p>There are no customer records in this application.</p>
    {% endif %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

pharmacyapp/templates/pharmacyapp/employee_detail.html
{% extends "base-generic.html" %}

{% block content %}
    <br>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/employee_detail_styles.css' %}">
    <h1>Employee</h1>
    <div style="margin: 10px;">
        <button class="cust-button" onclick="location.href='{% url "employee-update" employee.id %}';">Update Employee</button>
        <button class="cust-button" onclick="location.href='{% url "employee-delete" employee.id %}';">Delete Employee</button>
    </div>
    <div class="bord">
        <br>
        <h6>Name : <span> {{ employee.name }} </span> </h6>
        <h6>Address : <span> {{ employee.address }} </span> </h6>
        <h6>Phone No : <span> {{ employee.phone_no }} </span> </h6>
        <h6>Email : <span> {{ employee.email }} </span> </h6>
        <h6>Id Proof : <span> {{ employee.get_id_proof_display }} </span> </h6>
        <h6>Id Proof Unique No : <span> {{ employee.proof_unique_no }} </span> </h6>
        <br>
    </div>
{% endblock %}

pharmacyapp/templates/pharmacyapp/employee_form.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/employee_form_styles.css' %}">
    <div>
        <h1>Employee</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

pharmacyapp/templates/pharmacyapp/employee_list.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/employee_list_styles.css' %}">
    <div>
        <button class="cust-button" onclick="location.href='{% url 'employee-create' %}';">Create Employee</button>
    </div>
    <br>
    <h1>Employee</h1>
    <form method="get">
        <table>
        {{ filter.form.as_table }}
        </table>
        <input type="submit" />
    </form>
    {% if object_list %}
        <ul class="list-group">
        {% for employee in page_obj %}
            <li class="list-med-item list-group-item" style="background-color:#ECE5F0; border-radius: 50px; justify-content: center;">
                <div class="container">
                <div class="row" style="justify-content: space-around;">
                    <div class="row-sm">
                    <a href="{% url 'employee-detail' employee.id %}">{{ employee.name }}</a>
                    </div>
                    <div class="row-sm">
                        <button class="cust-button" onclick="location.href='{% url 'employee-delete' employee.id %}';">Delete</button>
                    </div>
                    <div class="row-sm">
                        <button class="cust-button" onclick="location.href='{% url 'employee-update' employee.id %}';">Update</button>
                    </div>
                </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    {% else %}
      <p>There are no dealer in this application.</p>
    {% endif %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

pharmacyapp/templates/pharmacyapp/medicine_form.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/medicine_form_styles.css' %}">
    <div>
        <h1>Medicine</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

pharmacyapp/templates/pharmacyapp/price_confirm_delete.html
{% extends "base-generic.html" %}

{% block content %}
<br>
<form method="post">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/price_confirm_delete_styles.css' %}">
    {% csrf_token %}
    <h1>Price Delete</h1>
    <p>Are you sure you want to delete ?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

pharmacyapp/templates/pharmacyapp/price_form.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/price_form_styles.css' %}">
    <div>
        <h1>Price</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

pharmacyapp/templates/pharmacyapp/todo_confirm_delete.html
{% extends "base-generic.html" %}

{% block content %}
<br>
<form method="post">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/todo_confirm_delete_styles.css' %}">
    {% csrf_token %}
    <h1>TODO Delete</h1>
    <p>Are you sure you want to delete "{{ object.title }}" this todo?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

pharmacyapp/templates/pharmacyapp/todo_form.html
{% extends "base-generic.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/todo_form_styles.css' %}">
    <div>
        <h1>TODO</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}